stages:
  preprocess:
    cmd: app_venv\Scripts\python.exe preprocess.py
    deps:
    - data/anime.csv
    - data/rating.csv
    params:
    - seed
    outs:
    - data/anime_clean.csv
    - data/anime_genre.csv
    - data/anime_train.csv
    - data/rating_clean.csv
    - weights/kmeans.pkl
    - weights/scaler.pkl
