stages:
  preprocess:
    cmd: data/rating.csv -p seed -o data/rating_clean, data/anime_clean.csv, 
      data/anime_genre.csv, data/anime_train.csv, weigts/kmeans.pkl, 
      weights/scaler.pkl 
      C:/Users/Михаил/Documents/venvs/gradio/Scripts/python.exe preprocess.py
    deps:
    - data/anime.csv,
